import argparse

parser = argparse.ArgumentParser(description="Ćwicze se argparsera tako")

parser.add_argument("file", help="Ścieżka do plika")
# parser.add_argument("-e", "--epochs", help="Liczba epok", type=int, action="append")
parser.add_argument(
    "-e", "--epochs", help="epohy", type=int, action="extend", nargs="*"
)
# parser.add_argument("-lr", "--learningrate", help="Learning rate", type=float)
# parser.add_argument("-bs", "--batch_size", default=32)
# parser.add_argument("-m", "--mode", choices=["SZYPKI", "WOLMY"])
# parser.add_argument("-ug", "--use_gpu", action="store_true")
# parser.add_argument("tables", nargs="+")
# parser.add_argument("-o", "--output", metavar="TO_CO_WYSZŁO")
# parser.add_argument("-d", "--dataset", required=True, help="ścieżka do datasetu")
# group = parser.add_mutually_exclusive_group()
# group.add_argument("-q", "--quiet", action="store_true")
# group.add_argument("-v", "--verbose", action="store_true")
# parser.add_argument("--log", nargs="?", default="info")
# parser.add_argument("-lrv", "--learning_rate_value", dest="LRValue")
# parser.add_argument("--version", action="version", version="v1.0.0")

args = parser.parse_args()

print(args)
# config = vars(args)

# print(args)
# print(args.file)
# print(args.epochs)
# print(args.learningrate)
# print(args.batch_size)
# print(args.mode)
# print(args.use_gpu)
# print(args.tables)
# print(args.output)
# print(args.dataset)
# print(args.quiet)
# print(args.verbose)
# print(args.log)
# print(args.LRValue)
# print(args.version)
# print(args.epochs)
# print(args.learningrate)
print(args.epochs)
